import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Button } from 'antd'
import HeaderComponent from '@/components/mainPage/header/header_component'
import GameComponent from '@/components/mainPage/game/game_component'

export default function Home() {
  return (
    <>
      <Head>
        <title>Trivia Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HeaderComponent />
        <GameComponent />
      </main>
    </>
  )
}